language: python
python:
  - "3.6"
dist: bionic
addons:
  snaps:
  - name: snapcraft
    confinement: classic

env:
  global:
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8

script:
  - sudo snapcraft --destructive-mode
