language: python
python:
  - "3.6"
dist: bionic
addons:
  snaps:
  - name: snapcraft
    confinement: classic

env:
  global:
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8

install:
  - sudo sed -i '/^deb/s/$/ universe/' /etc/apt/sources.list
  - sudo apt-get update

script:
  - sudo snapcraft --destructive-mode
