name: pi
version: 24-2
summary: Raspberry Pi gadget
description: |
  Support files for booting Raspberry Pi.
  This gadget snap supports the Raspberry Pi 2B, 3B, 3A+, 3B+, 4B, Compute
  Module 3, and the Compute Module 3+ universally.
type: gadget
base: core24
assumes: [kernel-assets]
platforms:
  rpi:
    build-on: arm64
    build-for: arm64
  rpi-amd64:
    build-on: amd64
    build-for: arm64

package-repositories:
  - type: apt
    ppa: snappy-dev/image

confinement: strict
grade: stable
parts:
  gadget:
    plugin: nil
    source: .
    override-build: |
      set -x
      
      # we only support arm64 for 24 for pi
      BUILD_ARCH_TRIPLET=aarch64-linux-gnu
      BUILD_SERIES=noble
      BUILD_ARCH="$(dpkg-architecture -t $BUILD_ARCH_TRIPLET -q DEB_HOST_ARCH)"
      
      # but only use the cross-compiling sources when actually cross compiling
      # as otherwise its just safer to use the build environment - it offers
      # much more flexibility.
      if [ "$CRAFT_ARCH_TRIPLET_BUILD_ON" = "x86_64-linux-gnu" ] || [ -z "$CRAFT_ARCH_TRIPLET_BUILD_ON" ]; then
        sed -i "/^deb/s/\bSERIES/$BUILD_SERIES/" ./helpers/cross-sources.list
        sed -i "/^deb/s/\bARCH\b/$BUILD_ARCH/" ./helpers/cross-sources.list
        OPTIONAL_ARGS="SERIES_HOST=\"$BUILD_SERIES\" SOURCES_HOST=\"./helpers/cross-sources.list\" SOURCES_D_HOST=\"./helpers\""
      fi
      
      make -C $CRAFT_PART_SRC core \
        DESTDIR=${CRAFT_PART_INSTALL} \
        SERIES="$BUILD_SERIES" \
        ARCH="$BUILD_ARCH" \
        ${OPTIONAL_ARGS:-}
    prime:
      - boot-assets/*
      - piboot.conf
    build-packages:
      - lsb-release
      - dpkg-dev
      - make
      - gnupg
      - dirmngr

slots:
  bcm-gpio-512:
    interface: gpio
    number: 512
  bcm-gpio-513:
    interface: gpio
    number: 513
  bcm-gpio-514:
    interface: gpio
    number: 514
  bcm-gpio-515:
    interface: gpio
    number: 515
  bcm-gpio-516:
    interface: gpio
    number: 516
  bcm-gpio-517:
    interface: gpio
    number: 517
  bcm-gpio-518:
    interface: gpio
    number: 518
  # GPIO 519 and 520 are by default in use for the SPI0 device
  # and dtparam=spi=on in config.txt-common must be changed
  # for these to be available.
  #  bcm-gpio-519:
  #    interface: gpio
  #    number: 519
  #  bcm-gpio-520:
  #    interface: gpio
  #    number: 520
  bcm-gpio-521:
    interface: gpio
    number: 521
  bcm-gpio-522:
    interface: gpio
    number: 522
  bcm-gpio-523:
    interface: gpio
    number: 523
  bcm-gpio-524:
    interface: gpio
    number: 524
  bcm-gpio-525:
    interface: gpio
    number: 525
  bcm-gpio-526:
    interface: gpio
    number: 526
  bcm-gpio-527:
    interface: gpio
    number: 527
  bcm-gpio-528:
    interface: gpio
    number: 528
  bcm-gpio-529:
    interface: gpio
    number: 529
  bcm-gpio-530:
    interface: gpio
    number: 530
  bcm-gpio-531:
    interface: gpio
    number: 531
  bcm-gpio-532:
    interface: gpio
    number: 532
  bcm-gpio-533:
    interface: gpio
    number: 533
  bcm-gpio-534:
    interface: gpio
    number: 534
  bcm-gpio-535:
    interface: gpio
    number: 535
  bcm-gpio-536:
    interface: gpio
    number: 536
  bcm-gpio-537:
    interface: gpio
    number: 537
  bcm-gpio-538:
    interface: gpio
    number: 538
  bcm-gpio-539:
    interface: gpio
    number: 539
  i2c-0:
    interface: i2c
    path: /dev/i2c-0
  i2c-1:
    interface: i2c
    path: /dev/i2c-1
  i2c-2:
    interface: i2c
    path: /dev/i2c-2
  i2c-3:
    interface: i2c
    path: /dev/i2c-3
  i2c-4:
    interface: i2c
    path: /dev/i2c-4
  i2c-5:
    interface: i2c
    path: /dev/i2c-5
  i2c-6:
    interface: i2c
    path: /dev/i2c-6
  bt-serial:
    interface: serial-port
    path: /dev/ttyAMA0
  ama1-serial:
    interface: serial-port
    path: /dev/ttyAMA1
  ama2-serial:
    interface: serial-port
    path: /dev/ttyAMA2
  ama3-serial:
    interface: serial-port
    path: /dev/ttyAMA3
  ama4-serial:
    interface: serial-port
    path: /dev/ttyAMA4
  ama5-serial:
    interface: serial-port
    path: /dev/ttyAMA5
  serial0:
    interface: serial-port
    path: /dev/ttyS0
  serial1:
    interface: serial-port
    path: /dev/ttyS1
  serial2:
    interface: serial-port
    path: /dev/ttyS2
  serial3:
    interface: serial-port
    path: /dev/ttyS3
  serial4:
    interface: serial-port
    path: /dev/ttyS4
  serial5:
    interface: serial-port
    path: /dev/ttyS5
  serial6:
    interface: serial-port
    path: /dev/ttyS6
  serial7:
    interface: serial-port
    path: /dev/ttyS7
  serial8:
    interface: serial-port
    path: /dev/ttyS8
  serial9:
    interface: serial-port
    path: /dev/ttyS9
  spidev0:
    interface: spi
    path: /dev/spidev0.0
  spidev1:
    interface: spi
    path: /dev/spidev0.1
  spidev1-0:
    interface: spi
    path: /dev/spidev1.0
  spidev1-1:
    interface: spi
    path: /dev/spidev1.1
  spidev2-0:
    interface: spi
    path: /dev/spidev2.0
  spidev2-1:
    interface: spi
    path: /dev/spidev2.1
  spidev3-0:
    interface: spi
    path: /dev/spidev3.0
  spidev3-1:
    interface: spi
    path: /dev/spidev3.1
  spidev4-0:
    interface: spi
    path: /dev/spidev4.0
  spidev4-1:
    interface: spi
    path: /dev/spidev4.1
  spidev5-0:
    interface: spi
    path: /dev/spidev5.0
  spidev5-1:
    interface: spi
    path: /dev/spidev5.1
  spidev6-0:
    interface: spi
    path: /dev/spidev6.0
  spidev6-1:
    interface: spi
    path: /dev/spidev6.1
  pwm0:
    interface: pwm
    chip-number: 0
    channel: 0
  pwm1:
    interface: pwm
    chip-number: 0
    channel: 1
