#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

#
# disable getty on tty1 to quiten down the console
#
SYSTEMDDIR="/root/writable/system-data/etc/systemd"
JOBDIR="${SYSTEMDDIR}/system"
SERVICENAME="getty@tty1.service"

[ -e "${JOBDIR}/${SERVICENAME}" ] || ln -s /dev/null "${JOBDIR}/${SERVICENAME}"
