#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

for x in $(cat /proc/cmdline); do
  case ${x} in
    splash)
      /bin/psplash &
    ;;
    *)
	;;
  esac
done

